services:
  - type: web
    name: ai-chat-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_CHAT_MODEL
        value: gemini-2.5-flash
      - key: GEMINI_STT_MODEL
        value: gemini-2.5-flash
